version: "3"
services:
  message-app:
    image: jerryvig/flask-instagram-images:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 750M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:5000"
    networks:
      - webnet
networks:
  webnet:
